### ISSUE TITLE
Meeting errors in demo.py when downloading llava

### ISSUE THREAD

**Issue by lulinliu** [WHU-USI3DV/VistaDream#19]
Hi Thank u for your work.
I met this errors in demo.py when loading llava into memory.
Do u have any ideas about this?
Thank u in advance.

/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/models/llava/configuration_llava.py:100: FutureWarning: The `vocab_size` argument is deprecated and will be removed in v4.42, since it can be inferred from the `text_config`. Passing this argument has no effect
  warnings.warn(
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  9.00it/s]
Traceback (most recent call last):
  File "/datadrive/VistaDream/we.py", line 21, in <module>
    processor = AutoProcessor.from_pretrained(
  File "/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/models/auto/processing_auto.py", line 319, in from_pretrained
    return processor_class.from_pretrained(
  File "/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/processing_utils.py", line 836, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/processing_utils.py", line 882, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 889, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2163, in from_pretrained
    return cls._from_pretrained(
  File "/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2397, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 157, in __init__
    super().__init__(
  File "/datadrive/VistaDream/conda_envs/vistadream/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 115, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum ModelWrapper at line 268080 column 3

**Comment by HpWang-whu** [comment]
Hi @lulinliu,
This issue might be caused by a version compatibility problem with transformers. You may try updating it to the latest version by 
```
pip install transformers==4.47.0
```
Some other package updates are also recommanded:
```
pip install accelerate==1.2.0
pip install diffusers==0.31.0
pip install huggingface-hub==0.26.3
```

Yours,
