### ISSUE TITLE
File Not Found: depth_pro.pt

### ISSUE THREAD

**Issue by HashingTag** [WHU-USI3DV/VistaDream#4]
Hello, when I try to run this in Google Colab, I get the following error:
```
Traceback (most recent call last):
  File "/content/VistaDream/demo.py", line 6, in <module>
    vistadream = Pipeline(cfg)
  File "/content/VistaDream/pipe/c2f_recons.py", line 30, in __init__
    self.reconstructor = Reconstruct_Tool(cfg)
  File "/content/VistaDream/pipe/reconstruct.py", line 19, in __init__
    self._load_model()
  File "/content/VistaDream/pipe/reconstruct.py", line 23, in _load_model
    self.pro_dpt = Depth_Pro_Tool(ckpt=self.cfg.model.mde.dpt_pro.ckpt,device='cpu')
  File "/content/VistaDream/ops/depth_pro.py", line 10, in __init__
    super().__init__(device, ckpt)
  File "/content/VistaDream/tools/DepthPro/command_pro_dpt.py", line 10, in __init__
    self._load_model()
  File "/content/VistaDream/tools/DepthPro/command_pro_dpt.py", line 21, in _load_model
    self.model, self.transform = depth_pro.create_model_and_transforms(config=cfg,device=self.device)
  File "/usr/local/lib/python3.10/dist-packages/depth_pro/depth_pro.py", line 135, in create_model_and_transforms
    state_dict = torch.load(config.checkpoint_uri, map_location="cpu")
  File "/content/VistaDream/tools/Fooocus/modules/patch.py", line 481, in loader
    raise ValueError(exp)
ValueError: [Errno 2] No such file or directory: "tools/DepthPro/checkpoints/depth_pro.pt'"
```

The checkpoint has already been downloaded to that location. I have double-checked, and it’s still the same error.

Is there any Colab python notebook for VistaDream that I can run?

**Comment by ngc-shj** [comment]
I encountered the same error. I was able to avoid it by adding single quotes like this:

```patch
-      ckpt: tools/DepthPro/checkpoints/depth_pro.pt'
+      ckpt: 'tools/DepthPro/checkpoints/depth_pro.pt'
```

**Comment by HpWang-whu** [comment]
I apologize for the issue caused by my carelessness and @ngc-shj is correct.
